#!/bin/bash
WATER="water"; STIR=".stir"; result=$((5#$(echo $WATER | tr 'water' '01234')) + $((5#$(echo $STIR | tr 'stir.' '01234'))))); echo $(printf %s $(echo $result | tr '0123456789ABC' 'abcdefghijklmnopqrstuvwxyz'))
